/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testjni_JNILoader */

#ifndef _Included_com_example_testjni_JNILoader
#define _Included_com_example_testjni_JNILoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testjni_JNILoader
 * Method:    GetNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_testjni_JNILoader_GetNativeString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
